services:
  book_catalog:
    build: 
      context: ./book_catalog
    image: book_catalog1:1
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://project_part3_i5d6_user:UBbDYZkO6YovOXoJJnNwqIIRHDMdRKHD@dpg-crvrpibtq21c738pjprg-a.oregon-postgres.render.com/project_part3_i5d6

  inventory_management:
    build: 
      context: ./inventory_management
    image: inventory_management1:1
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://project_part3_i5d6_user:UBbDYZkO6YovOXoJJnNwqIIRHDMdRKHD@dpg-crvrpibtq21c738pjprg-a.oregon-postgres.render.com/project_part3_i5d6
